language: R

r:
  - oldrel
  - release
  - devel

before_script:
    - Rscript -e 'install.packages("pkgdown")'
    - wget -qO- https://bootstrap.pypa.io/get-pip.py | sudo python3
    - sudo apt-get install python3-rpy2
    - python3 -m pip install --user jupyter nbconvert
    - scripts/document.sh

after_success:
    - Rscript -e 'covr::codecov()'

