name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }} ${{ matrix.r }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        r: [3.6, 4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r }}
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Prepare tests
        run: ./scripts/prepare_for_tests.sh
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Report coverage
        run: Rscript -e 'covr::codecov()'
